# Generated by Django 4.0.2 on 2022-02-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0002_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='socialApp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
