# Generated by Django 4.0.2 on 2022-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0002_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
