# Generated by Django 4.0.2 on 2022-03-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0003_alter_posts_options_alter_posts_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
