# Generated by Django 4.0.2 on 2022-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0003_userprofile_follows_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='followed_by',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='following', to='socialApp.UserProfile'),
        ),
    ]
