# Generated by Django 4.0.2 on 2022-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0004_alter_posts_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
