# Generated by Django 4.0.2 on 2022-03-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0004_rename_followers_userprofile_followed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followed_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
