# Generated by Django 4.0.2 on 2022-03-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0004_userprofile_profile_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_thumb',
        ),
    ]
