# Generated by Django 4.0.2 on 2022-03-05 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialApp', '0005_remove_userprofile_followed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.CharField(blank=True, max_length=50)),
                ('follows', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
