# Generated by Django 4.0.2 on 2022-03-20 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0005_remove_userprofile_profile_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socialApp.userprofile'),
        ),
    ]
