# Generated by Django 4.0.2 on 2022-03-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0006_posts_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='profile_image',
        ),
    ]
