# Generated by Django 4.0.2 on 2022-03-05 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialApp', '0006_remove_userprofile_followed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follows', to='socialApp.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
