# Generated by Django 4.0.2 on 2022-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0006_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
